package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/Alfeus22/puskesmas-api/graph/model"
	"github.com/Alfeus22/puskesmas-api/internal/middleware"
	"github.com/Alfeus22/puskesmas-api/pkg/utils"
)

// BuatPasien is the resolver for the buatPasien field.
func (r *mutationResolver) BuatPasien(ctx context.Context, input model.PasienInput) (*model.Pasien, error) {
	pasien, err := r.PasienService.DaftarPasienBaru(input.Nik, input.NamaLengkap, input.AlergiObat)
	if err != nil {
		return nil, err
	}
	hasil := &model.Pasien{
		ID:          pasien.ID,
		Nik:         pasien.NIK,
		NamaLengkap: pasien.NamaLengkap,
		AlergiObat:  pasien.AlergiObat,
	}
	return hasil, nil
}

// UbahPasien is the resolver for the ubahPasien field.
func (r *mutationResolver) UbahPasien(ctx context.Context, id string, input model.PasienInput) (*model.Pasien, error) {
	ubahPasien, err := r.PasienService.UpdatePasien(id, input.Nik, input.NamaLengkap, input.AlergiObat)
	if err != nil {
		return nil, err
	}
	update := &model.Pasien{
		ID:          ubahPasien.ID,
		Nik:         ubahPasien.NIK,
		NamaLengkap: ubahPasien.NamaLengkap,
		AlergiObat:  ubahPasien.AlergiObat,
	}

	return update, nil
}

// HapusPasien is the resolver for the hapusPasien field.
func (r *mutationResolver) HapusPasien(ctx context.Context, id string) (*model.Pasien, error) {

	user := middleware.ForContext(ctx)
	if user == nil {
		return nil, errors.New("silahkan login dulu")
	}
	if user.Role != "admin" {
		return nil, errors.New("akses ditolak")
	}
	hapusPasien, err := r.PasienService.SoftDeletePasien(id)
	if err != nil {
		return nil, err
	}

	softDelete := &model.Pasien{
		ID: hapusPasien.ID,
	}
	return softDelete, nil

}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, username string, role string) (*string, error) {
	token, err := utils.GenerateToken(username, role)
	if err != nil {
		return nil, err
	}
	return &token, nil

}

// ProfilPasien is the resolver for the profilPasien field.
func (r *queryResolver) ProfilPasien(ctx context.Context, id string) (*model.Pasien, error) {
	dataPasien, err := r.PasienService.GetById(id)
	if err != nil {
		return nil, err
	}

	hasil := &model.Pasien{
		ID:          dataPasien.ID,
		Nik:         dataPasien.NIK,
		NamaLengkap: dataPasien.NamaLengkap,
	}
	if dataPasien.AlergiObat != nil {
		hasil.AlergiObat = utils.NullableString(*dataPasien.AlergiObat)
	}
	return hasil, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
