package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/Alfeus22/puskesmas-api/graph/model"
	"github.com/Alfeus22/puskesmas-api/internal/middleware"
	"github.com/Alfeus22/puskesmas-api/internal/storage"
	"github.com/Alfeus22/puskesmas-api/pkg/utils"
	"github.com/google/uuid"
)

// BuatPasien is the resolver for the buatPasien field.
func (r *mutationResolver) BuatPasien(ctx context.Context, input model.PasienInput) (*model.Pasien, error) {
	pasienBaru := &storage.Pasien{
		ID:          uuid.New().String(),
		NIK:         input.Nik,
		NamaLengkap: input.NamaLengkap,
	}
	if input.AlergiObat != nil {
		pasienBaru.AlergiObat = input.AlergiObat
	}
	tx, err := r.PasienStorage.StartTransaction()
	if err != nil {
		return nil, err
	}

	defer tx.Rollback()

	err = r.PasienStorage.CreatePasienTx(tx, pasienBaru)
	if err != nil {
		return nil, err
	}

	err = tx.Commit()
	if err != nil {
		return nil, err
	}

	hasil := &model.Pasien{
		ID:          pasienBaru.ID,
		Nik:         pasienBaru.NIK,
		NamaLengkap: pasienBaru.NamaLengkap,
	}
	if pasienBaru.AlergiObat != nil {
		hasil.AlergiObat = utils.NullableString(*pasienBaru.AlergiObat)
	}
	return hasil, nil
}

// UbahPasien is the resolver for the ubahPasien field.
func (r *mutationResolver) UbahPasien(ctx context.Context, id string, input model.PasienInput) (*model.Pasien, error) {
	pasienUpdate := &storage.Pasien{
		NIK:         input.Nik,
		NamaLengkap: input.NamaLengkap,
	}
	if input.AlergiObat != nil {
		pasienUpdate.AlergiObat = input.AlergiObat
	}

	tx, err := r.PasienStorage.StartTransaction()
	if err != nil {
		return nil, err
	}

	defer tx.Rollback()

	err = r.PasienStorage.UpdatePasienTx(tx, id, pasienUpdate)
	if err != nil {
		return nil, err
	}

	err = tx.Commit()
	if err != nil {
		return nil, err
	}

	hasil := &model.Pasien{
		ID:          id,
		Nik:         pasienUpdate.NIK,
		NamaLengkap: pasienUpdate.NamaLengkap,
	}
	if pasienUpdate.AlergiObat != nil {
		hasil.AlergiObat = utils.NullableString(*pasienUpdate.AlergiObat)
	}
	return hasil, nil
}

// HapusPasien is the resolver for the hapusPasien field.
func (r *mutationResolver) HapusPasien(ctx context.Context, id string) (*model.Pasien, error) {

	user := middleware.ForContext(ctx)
	if user == nil {
		return nil, errors.New("akses ditolak silahkan login terlebih dahulu")
	}
	if user.Role != "admin" {
		return nil, errors.New("akes ditolak: khusus admin yang dapat menghapus data")
	}

	dataPasien, err := r.PasienStorage.GetByID(id)
	if err != nil {
		return nil, err
	}

	tx, err := r.PasienStorage.StartTransaction()
	if err != nil {
		return nil, err
	}

	defer tx.Rollback()

	err = r.PasienStorage.SoftDeleteTx(tx, id)
	if err != nil {
		return nil, err
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}

	hasil := &model.Pasien{
		ID:          dataPasien.ID,
		Nik:         dataPasien.NIK,
		NamaLengkap: dataPasien.NamaLengkap,
	}
	if dataPasien.AlergiObat != nil {
		hasil.AlergiObat = utils.NullableString(*dataPasien.AlergiObat)
	}
	return hasil, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, username string, role string) (*string, error) {
	token, err := utils.GenerateToken(username, role)
	if err != nil {
		return nil, err
	}
	return &token, nil

}

// ProfilPasien is the resolver for the profilPasien field.
func (r *queryResolver) ProfilPasien(ctx context.Context, id string) (*model.Pasien, error) {
	dataPasien, err := r.PasienStorage.GetByID(id)
	if err != nil {
		return nil, err
	}

	hasil := &model.Pasien{
		ID:          dataPasien.ID,
		Nik:         dataPasien.NIK,
		NamaLengkap: dataPasien.NamaLengkap,
	}
	if dataPasien.AlergiObat != nil {
		hasil.AlergiObat = utils.NullableString(*dataPasien.AlergiObat)
	}
	return hasil, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
