# GraphQL schema example
#
# https://gqlgen.com/getting-started/

type Pasien{
  id: ID!
  nik: String!
  nama_lengkap: String!
  alergi_obat: String
}
type Dokter{
  id: ID!
  nid: String!
  nama: String!
}
type Kunjungan{
  id: ID!
  id_dokter: ID!
  id_pasien: ID!
  tanggal_kunjungan: String!
  keluhan: String
  dokter: Dokter!
  pasien: Pasien!
}

type Query{
  profilPasien(id: ID!): Pasien!
  profilDokter(id : ID!): Dokter!
  kunjunganByPasien(idPasien: ID!): [Kunjungan!]!
  kunjunganByDokter(idDokter: ID!): [Kunjungan!]!
}
input DokterInput {
  nid : String!
  nama : String!
}
input PasienInput{
  nik: String!
  nama_Lengkap: String!
  alergi_obat: String
}
input KunjunganInput{
  id_dokter: ID!
  id_pasien: ID!
  tanggal_kunjungan: String!
  keluhan: String
}

type Mutation{

  buatDokter(input: DokterInput!): Dokter!
  ubahDokter(id: ID!, input: DokterInput!): Dokter!

  buatPasien(input: PasienInput!): Pasien!
  ubahPasien(id: ID!, input: PasienInput!): Pasien!
  hapusPasien(id: ID!): Pasien!

  buatKunjungan(input: KunjunganInput!): Kunjungan!
  hapusKunjungan(id: ID!): Kunjungan!

  login(username: String!, role: String!): String
}

