# GraphQL schema example
#
# https://gqlgen.com/getting-started/

type Pasien{
  id: ID!
  nik: String!
  nama_lengkap: String!
  alergi_obat: String
}
type Dokter{
  id: ID!
  nid: String!
  nama: String!
}

type Query{
  profilPasien(id: ID!): Pasien!
  profilDokter(id : ID!): Dokter!

}
input DokterInput {
  nid : String!
  nama : String!
}
input PasienInput{
  nik: String!
  nama_Lengkap: String!
  alergi_obat: String
}

type Mutation{

  buatDokter(input: DokterInput!): Dokter!

  buatPasien(input: PasienInput!): Pasien!
  ubahPasien(id: ID!, input: PasienInput!): Pasien!
  hapusPasien(id: ID!): Pasien!

  login(username: String!, role: String!): String
}

