// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Dokter struct {
	ID   string `json:"id"`
	Nid  string `json:"nid"`
	Nama string `json:"nama"`
}

type DokterInput struct {
	Nid  string `json:"nid"`
	Nama string `json:"nama"`
}

type Mutation struct {
}

type Pasien struct {
	ID          string  `json:"id"`
	Nik         string  `json:"nik"`
	NamaLengkap string  `json:"nama_lengkap"`
	AlergiObat  *string `json:"alergi_obat,omitempty"`
}

type PasienInput struct {
	Nik         string  `json:"nik"`
	NamaLengkap string  `json:"nama_Lengkap"`
	AlergiObat  *string `json:"alergi_obat,omitempty"`
}

type Query struct {
}
